set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi_0]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso_0]
set_property IOSTANDARD LVCMOS33 [get_ports spi_sclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports spi_ss_0]
set_property PACKAGE_PIN M15 [get_ports spi_mosi_0]
set_property PACKAGE_PIN L14 [get_ports spi_miso_0]
set_property PACKAGE_PIN M14 [get_ports spi_sclk_0]
set_property PACKAGE_PIN L15 [get_ports spi_ss_0]
set_property PULLUP TRUE [get_ports spi_mosi_0]
set_property PULLUP TRUE [get_ports spi_miso_0]
set_property PULLUP TRUE [get_ports spi_sclk_0]
set_property PULLUP TRUE [get_ports spi_ss_0]

# Test LED
set_property IOSTANDARD LVCMOS33 [get_ports led_test_0]
set_property PACKAGE_PIN E13 [get_ports led_test_0]
